[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest]
testpaths = ["annzarro/tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"

[tool.pylint]
disable = ["C0111", "C0301", "C0103"]
max-line-length = 100
good-names = ["i", "j", "k", "e", "f", "id", "_", "X"]

[tool.black]
line-length = 100
target-version = ["py38"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100